# Generated by Django 2.2.6 on 2019-11-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=2)),
                ('population', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=3)),
                ('population', models.IntegerField(default=0)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.State')),
            ],
        ),
    ]
