# Generated by Django 2.2.7 on 2019-11-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0003_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('sports and recreation', 'sports and recreation'), ('education', 'education'), ('health', 'health'), ('food', 'food'), ('admin', 'admin'), ('work', 'work')], max_length=100),
        ),
    ]
